version: '3.8'

services:
  app:
    build: .
    container_name: mastermind_php_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_PORT=${DB_PORT}
      - JWT_SECRET=${JWT_SECRET}

  postgres:
    image: postgres:15
    container_name: mastermind_php_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_php_data:/var/lib/postgresql/data
      - ./Database/migration.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_php_data: